# Generated by Django 3.1 on 2021-01-19 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakerapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedbackData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
                ('data', models.DateField(max_length=100)),
                ('feedback', models.TextField()),
            ],
        ),
    ]
